default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: embarca_test_development

test:
  <<: *default
  database: embarca_test_test

production:
  <<: *default
  database: embarca_test_production
  username: embarca_test
  password: <%= ENV['EMBARCA_TEST_DATABASE_PASSWORD'] %>
